#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
chdir(__DIR__ . DS . ".." . DS . ".." . DS . ".." . DS);
$vendor = getcwd() . DS . "vendor";
if(is_dir($vendor)){
    $rootDir = getcwd();
    define('_ROOT', $rootDir);
    define('_isPROJECT', true);
}else{
    chdir(".." . DS . ".." . DS . ".." . DS);
    $vendor = getcwd() . DS . "vendor";
    if($vendor){
        $rootDir = getcwd();
        define('_ROOT', $rootDir);
        define('_isPROJECT', false);
    } else {
        echo "ERROR: root path not found";
    }
}


$loader = require_once _ROOT . DS . "vendor" . DS . "autoload.php";

use Core\Scripts\corecmd;

$cmd = new corecmd($argv, $argc);

